### ISSUE TITLE
On deinit warning, also log location where the PromiseSource was created

### ISSUE THREAD

**Issue by mac-cain13** [tomlokhorst/Promissum#14]
This would be very valuable when trying to fix the error, maybe only capture/print this info in debug mode since it is a bit sensitive info.

The magic constants like `__FUNCTION__` should make this possible.

**Comment by tomlokhorst** [comment]
This is indeed very useful.

We should also think about how to handle PromiseSources created by combinators like `map` and `flatMap`.

Promises often go through a stack combinators, like: `somePromise.map(...).mapError(...).flatMapResult(...)`.
We probably want to print the entire stack, since either end isn't sufficient information. Especially when a promise has been passed around a bunch.

**Comment by mac-cain13** [comment]
Yeah, agreed. I think a promise based on another PromiseSource should print the location of the origional source. Or if possible the whole stacktrace indeed, but I don't know how much value that adds.

**Comment by tomlokhorst** [comment]
This is being worked on in https://github.com/tomlokhorst/Promissum/pull/19
